# Project information
site_name: Slyr Documenation
site_description: >-
  This site contains documentation about Slyr
site_url: https://github.com/north-road/slyr

# Repository
repo_name: north-road/slyr
repo_url: https://github.com/north-road/slyr
edit_uri: https://github.com/north-road/slyr

# Theme configuration
theme:
  name: material
  custom_dir: docs/theme_overrides/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
  logo: assets/modelbaker_icon.svg
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        primary: white


# Page tree
nav:
  - Home: index.md

markdown_extensions:
  - attr_list
  - def_list
  - admonition

plugins:
  - i18n:
      default_language: en
      languages:
        en: English