name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Required Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS_TESTING.txt

      - name: Format (ruff)
        run: |
          ruff format --check --diff slyr_community
